import type { Metadata } from "next";
import { Poppins, Codystar } from "next/font/google";
import "@/styles/globals.css";
import { ClientProviders } from "@/context/client-provider";
import { Toaster } from "@/components/ui/sonner";

const poppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "400", "500", "600", "800"],
});

const codystartFont = Codystar({
  variable: "--font-codystar",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppinsFont.variable} ${codystartFont.variable}  antialiased`}
      >
        <ClientProviders>{children}</ClientProviders>
        <Toaster richColors />
      </body>
    </html>
  );
}
